### ISSUE TITLE
Numpy import error

### ISSUE THREAD

**Issue by cshr25** [udacity/RoboND-Perception-Exercises#10]
Hi, guys, I am trying to run the first exercise performing Voxel Grid Downsampling. I believed I have fully installed the whole package but got this message:

ImportError: numpy.core.multiarray failed to import

I have searched some solutions on google like reinstall numpy but it didn't work. Any suggestions?

The full error log is attached:

Traceback (most recent call last):
  File "RANSAC.py", line 2, in <module>
    import pcl
  File "/usr/local/lib/python2.7/dist-packages/python_pcl-0.2-py2.7-linux-x86_64.egg/pcl/__init__.py", line 3, in <module>
    from ._pcl import *
  File "pcl/_pcl_172.pyx", line 30, in init pcl._pcl (pcl/_pcl_172.cpp:94748)
  File "__init__.pxd", line 989, in numpy.import_array (pcl/_pcl_172.cpp:83387)
ImportError: numpy.core.multiarray failed to import

**Comment by cshr25** [comment]
Hi guys I got this issue fixed: I downloaded the whole repository again in my virtual machine and it worked. What I did before was using git clone in virtual machine's command prompt. Not sure why that didn't work out.
