### ISSUE TITLE
fix outlier filter

### ISSUE THREAD

**Issue by horagong** [udacity/RoboND-Perception-Exercises#18]
I got this error.
```
Traceback (most recent call last):
  File "RANSAC.py", line 70, in <module>
    outlier_filter = cloud_filtered.make_statistical_outlier_filter()
  File "pcl/pxi/PointCloud_PointXYZRGB_180.pxi", line 289, in pcl._pcl.PointCloud_PointXYZRGB.make_statistical_outlier_filter (pcl/_pcl_180.cpp:70034)
  File "pcl/pxi/Filters/StatisticalOutlierRemovalFilter.pxi", line 135, in pcl._pcl.StatisticalOutlierRemovalFilter_PointXYZRGB.__cinit__ (pcl/_pcl_180.cpp:23989)
TypeError: __cinit__() takes exactly 1 positional argument (0 given)
```

You fixed outlier filter only for 172. It was ok with the same fix(https://github.com/udacity/RoboND-Perception-Exercises/commit/d17bcd4747026fb81e1fe0d7db7c804a86860792) to the followings.
python-pcl/pcl/pxi/PointCloud_PointXYZ*.pxi
python-pcl/pcl/pxi/Filters/StatisticalOutlierRemovalFilter*.pxi

**Comment by charlescc9** [comment]
same issue; any resolution?

**Comment by mnbf9rca** [comment]
look at XYZRGB_to_XYZ in pcl_helper.py

**Comment by anubhav1772** [comment]
I am facing the same issue, did you able to solve the problem?

**Comment by shivammalviya712** [comment]
Has anyone solved it? 
Please, help if you have solved
